# Generated by Django 3.2.18 on 2023-05-06 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], max_length=11)),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=11)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='agent', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('assigned', 'Assigned'), ('reassigned', 'Re-assigned'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('reopened', 'Re-opened')], max_length=10)),
                ('comment', models.TextField()),
                ('ticket', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portal.ticket')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostics_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('enrollment_url', models.CharField(blank=True, max_length=200, null=True)),
                ('enrollment_group', models.CharField(blank=True, max_length=50, null=True)),
                ('awcm_status', models.CharField(max_length=50)),
                ('awcm_link', models.URLField(blank=True, null=True)),
                ('cn_status', models.BooleanField(default=False)),
                ('ds_status', models.BooleanField(default=False)),
                ('app_catalog', models.BooleanField(default=False)),
                ('service_status_indicator', models.CharField(blank=True, max_length=200, null=True)),
                ('service_status_description', models.CharField(blank=True, max_length=200, null=True)),
                ('ticket', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portal.ticket')),
            ],
        ),
    ]
