name: Monthly merge Staging into Main

on:
  schedule:
    - cron:  '0 0 1 * *'
  workflow_call:
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config --global user.email "patrick.pulfer1@gmail.com"
          git config --global user.name "patrickpulfer"

      - name: Merge Staging into Main branch
        run: |
          git fetch origin
          git checkout main
          git merge --no-edit origin/staging
          git push origin main
