name: Releae & Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DOCKER_HOST }}
          username: ${{ secrets.DOCKER_USERNAME }}
          port: ${{ secrets.DOCKER_PORT }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          script: |
            ./auto-deploy.sh
            exit
            exit

  check_deployment:
    needs: deployment
    runs-on: ubuntu-latest
    steps:
    - name: Check URL Status
      uses: gpuliyar/check-url-action@v1.0.1
      with:
        url: http://178.79.178.78/
        init-delay: 1000
        retry-count: 1
        retry-delay: 1000
        codes-allowed: 200,201,202

  release:
    needs: check_deployment
    runs-on: ubuntu-latest
    steps:
    - name: Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: ${{ secrets.API_GITHUB_TOKEN }}
        automatic_release_tag: "latest"
        prerelease: false
        title: "Release Build"

  notification_email:
    needs: check_deployment
    runs-on: ubuntu-latest
    steps:
    - name: Send notification email
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: GitHub Actions - Deployment complete
        body: Deployment complete!
        from: ${{ secrets.EMAIL_FROM }}
        to: ${{ secrets.EMAIL_TO }}