name: Python Security Check using Bandit

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: ["main", "staging", "patrickpulfer-patch-2"]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ./django_project
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Python security check using Bandit
        uses: Joel-hanson/bandit-report-artifacts@V1
        with:
          python_version: ${{ matrix.python-version }}
          project_path: ./django_project
          ignore_failure: true

      - name: Security check report artifacts
        uses: actions/upload-artifact@v1
        # if: failure()
        with:
          name: Security report
          path: output/security_report.txt