name: Django CI & Postgres Test

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [ "main", "staging", "patrickpulfer-patch-1" ]
  pull_request:
    branches: [ "main", "staging" ]

jobs:
  django_test:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ./django_project

    env:
      SECRET_KEY: test-key-not-production
      POSTGRES_DB: dockerdc
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: myuser
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      DB_IGNORE_SSL: "true"

    services:
      postgres_main:
        image: postgres:13
        env:
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: psycopg2 workaround
        run: |
          sudo apt-get install libpq-dev
          pip3 install psycopg2
      - name: Database Migration
        run: |
          python manage.py makemigrations core
          python manage.py makemigrations portal
          python manage.py migrate core
          python manage.py migrate portal

      - name: Run Tests
        run: |
          python manage.py test